### ISSUE TITLE
[Accessibility][Screen reader]: In Scan mode user is not able to close the 'Contextual menu' using 'Esc key'. (Bug 7)

### ISSUE THREAD

**Issue by jdhuntington** [OfficeDev/office-ui-fabric-react#10833]
Tracking all of the issues brought up with the 08/24 accessibility pass on Contextual Menu  control
Details on individual bugs can be found on [SharePoint](https://microsoft-my.sharepoint.com/:x:/r/personal/v-amaver_microsoft_com/_layouts/15/Doc.aspx?sourcedoc=%7Bcef6201c-bd85-44b6-a2d3-3784248461e0%7D&action=default&uid=%7BCEF6201C-BD85-44B6-A2D3-3784248461E0%7D&ListItemId=1259&ListId=%7B395E1ECB-5002-440E-81C5-6A090E98077C%7D&odsp=1&env=prodbubble)

Breakout of issue #6360

**Comment by dzearing** [comment]
@joschect Is this resolved with your recent fix?

**Comment by joschect** [comment]
@dzearing no, this still occurs, this is related to scan mode. Based on what I can see all of our menus should dismiss immediately if the user tries to interact with scan mode.

**Comment by xugao** [comment]
this bug repros in Edge not Chrome. Something to do with keydown event not being fired/bubbled up (therefore menu is not closing on `esc`. will explore how to best fix this

**Comment by xugao** [comment]
this issue only repros on Edge with screen reader scan mode. i'm going to downgrade this bug to a p3. The root cause of the keyboard event not triggering is currently unclear to me. will dig more later

**Comment by khmakoto** [comment]
This is an issue with how scan mode works on Edge:

>In your case specifically, when Narrator tries to drag/move text cursor inside the menu, Edge shifts system focus to the entire webpage pane. This basically means that:
> - Your menu element no longer receives input,
> - ESC that normally closes the menu is never "seen" by it.
>
>Chrome, for instance, does -- more or less -- what I described and shifts system focus to the element that can be focused by keyboard and contains the text position that the AT tries to move text cursor to.

This is by design in Edge.

**Comment by xugao** [comment]
hmm interesting. thanks @khmakoto for pointing out
