### ISSUE TITLE
ShimmeredDetailList columns do not render sort arrow when setting isSorted property

### ISSUE THREAD

**Issue by SteveJerbs** [OfficeDev/office-ui-fabric-react#11163]
### Environment Information

- **Package version(s)**: 7.56.1

https://codepen.io/cjmelnick/pen/WNNgZze?editors=1001

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low)

Products/sites affected: (if applicable)

**Comment by kenotron** [comment]
When you change the state, you have to clone the column data. I've fixed up the codepen for you for reference:
https://codepen.io/kenotron/pen/mddGXrL

![image](https://user-images.githubusercontent.com/34725/68722279-d0bd6700-0569-11ea-837a-0d8a16f1a811.png)

```
const newColumns = [...columns]
```

is the key here.

**Comment by SteveJerbs** [comment]
Thanks for the quick response.  That seemed to have fixed the code pen issue but when I made the same change in the application I am experiencing the issue in the issue persisted.  I ended up solving this issue by importing and calling the 'InitializeIcons' method, which means the sort arrows must be icons.
