### ISSUE TITLE
Components Documentation Broken

### ISSUE THREAD

**Issue by ndugger** [OfficeDev/office-ui-fabric-react#1289]
Seemingly half of the component pages on the documentation site are "broken". I'm seeing a JS error in my console:

http://dev.office.com/fabric#/components/commandbar

    Uncaught TypeError: Cannot read property 'call' of undefined
        at e (static2.sharepointonline.com/files/fabric/fabric-website/dist/fabric-site.min.js:1)
        at static2.sharepointonline.com/files/fabric/fabric-website/dist/fabric-site.min.js:1
        at window.webpackJsonp (static2.sharepointonline.com/files/fabric/fabric-website/dist/fabric-site.min.js:1)
        at static2.sharepointonline.com/files/fabric/fabric-website/dist/fabric-site-18.min.js:1

I am on Chrome, version 56.0.2924.87 (64-bit)

**Comment by mikewheaton** [comment]
Thank you for reporting this, @ndugger, we're investigating now.

**Comment by mikewheaton** [comment]
We've reverted the recent changes to the website that caused this issue. It should be working again shortly.

**Comment by ndugger** [comment]
Any idea on what "shortly" could mean? I've been refreshing the page every few minutes, but it's still broken.

**Comment by mikewheaton** [comment]
It's hard to say, as the broken files are now cached by the CDN. In the meantime you may want to [build the documentation locally](https://github.com/OfficeDev/office-ui-fabric-react#view-the-docs). Sorry for the trouble here.
