### ISSUE TITLE
Warnings when doing webpack

### ISSUE THREAD

**Issue by LeopoldLerch** [OfficeDev/office-ui-fabric-react#2644]
just updated to 4.37.5 and the warnings are still there when doing webpack:

```bash
WARNING in ./node_modules/@uifabric/utilities/lib/string.js
(Emitted value instead of an instance of Error) Cannot find SourceMap '../src/string.js.map': Error: Can't resolve '../src/string.js.map' in 'C:\P
rojekte\DAP\DAP\Webkomponenten\node_modules\@uifabric\utilities\lib'
 @ ./node_modules/@uifabric/utilities/lib/index.js 31:21-40
 @ ./node_modules/office-ui-fabric-react/lib/Utilities.js
 @ ./Banner/Banner.tsx
 @ ./BodyStartSeite/BodyStartSeite.tsx
 @ multi ./BodyStartSeite/BodyStartSeite

WARNING in ./node_modules/@uifabric/utilities/lib/warn.js
(Emitted value instead of an instance of Error) Cannot find SourceMap '../src/warn.js.map': Error: Can't resolve '../src/warn.js.map' in 'C:\Proje
kte\DAP\DAP\Webkomponenten\node_modules\@uifabric\utilities\lib'
 @ ./node_modules/@uifabric/utilities/lib/index.js 32:21-38
 @ ./node_modules/office-ui-fabric-react/lib/Utilities.js
 @ ./Banner/Banner.tsx
 @ ./BodyStartSeite/BodyStartSeite.tsx
 @ multi ./BodyStartSeite/BodyStartSeite
```
(that´s just a example part of it, there are much more like that)

same issue that should have been solved in issue 2610

**Comment by dzearing** [comment]
This was an error in @uifabric/utilities 4.10.1, which was fixed in 4.10.2.

Can you look at what version you have installed?

**Comment by LeopoldLerch** [comment]
I have utilities version 4.10.2 and the error is still there. I looked into it and the map files are located in the lib folder. 
However, the error mentions, that it is looking for them in a"src"-folder, which is not there.

**Comment by OneCyrus** [comment]
same problem here

**Comment by dzearing** [comment]
I just did these steps:

```bash
create-react-app my-app --scripts-version=react-scripts-ts
cd my-app
yarn add office-ui-fabric-react
```

Then, in App.tsx, I imported the fabric button and rendered.

```tsx
import * as React from 'react';
import './App.css';
import { Fabric } from 'office-ui-fabric-react/lib/Fabric';
import { PrimaryButton } from 'office-ui-fabric-react/lib/Button';

class App extends React.Component {
  render() {
    return (
      <Fabric className="App">
        <PrimaryButton text="I am a button" />
      </Fabric>
    );
  }
}

export default App;
```

This generates no errors and renders correctly. So @OneCyrus  or @LeopoldLerch , could you provide a sample project which generates the error? It is likely that there is some sort of package.json issue here where perhaps there is a nested dependency.

**Comment by dzearing** [comment]
Also it could be how your source-map setup in webpack.config.js is. If you could provide that in a gist or something that could help.

**Comment by dzearing** [comment]
I got a repro and am trying a fix.

**Comment by dzearing** [comment]
We should be good now. I just worked with a partner to validate that the sourcemaps work as before in these versions:

office-ui-fabric-react: 4.37.7
@uifabric/styling: 0.21.1,
@uifabric/utilities: 4.11.1

**Comment by OneCyrus** [comment]
looks good. it works again here.

thanks!

**Comment by LeopoldLerch** [comment]
works here again too


2017-08-30 8:28 GMT+02:00 Daniel Gut <notifications@github.com>:

**Comment by dzearing** [comment]
Thanks guys!
