### ISSUE TITLE
When hitting Escape in IE, all ContextualMenus close instead of just closing the current submenu

### ISSUE THREAD

**Issue by kelseyyoung** [OfficeDev/office-ui-fabric-react#4550]
### Bug Report

- __Package version(s)__: (5.81.1)
- __Browser and OS versions__: (IE Only)

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes)

Requested priority: (Normal) 

Products/sites affected: (if applicable)

#### Describe the issue:

In IE, if you open a submenu in a ContextualMenu then hit Escape, all menus close instead of just the current submenu

#### Actual behavior:

See below GIF, using the [Fabric Demo page](https://developer.microsoft.com/en-us/fabric#/components/contextualmenu) in IE 11

![contextualmenuie](https://user-images.githubusercontent.com/4252452/38756189-7f3f5442-3f1d-11e8-9062-32d5b4ccc667.gif)

#### Expected behavior:

See below GIF, using the [Fabric Demo page](https://developer.microsoft.com/en-us/fabric#/components/contextualmenu) in Chrome

![contextualmenuchrome](https://user-images.githubusercontent.com/4252452/38756201-84584204-3f1d-11e8-8310-2415aca159fc.gif)

**Comment by KevinTCoughlin** [comment]
I'm taking a look at this (can't self assign yet)

**Comment by KevinTCoughlin** [comment]
Currently blocked by #4712

**Comment by kelseyyoung** [comment]
@KevinTCoughlin since #4712 is now resolved, what's the status on this?

**Comment by KevinTCoughlin** [comment]
We should leave this open. This is still an issue in IE on the Fabric site and likely elsewhere -- just confirmed w/ OUFR `v6.20.0`. It has something to do with event propagation differing in IE vs other browsers I believe.

You can repro by opening the [ContextualMenu example](https://developer.microsoft.com/en-us/fabric#/components/contextualmenu) with a submenu, expanding the submenu and then pressing "ESC".
