### ISSUE TITLE
Modal focus trap gets broken by having an iframe as the last element in it

### ISSUE THREAD

**Issue by Anschur** [OfficeDev/office-ui-fabric-react#4649]
### Bug Report

- __Package version(s)__:
	- office-ui-fabric-react: "5.49.3"
	- react: "15.4.2"

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: High

Products/sites affected:
- SP Home [Search](https://microsoft.sharepoint.com/_layouts/15/sharepoint.aspx?q=Fabric&v=search%2Ffiles) (Modal used for the preview that appears when clicking on a office file result)

#### Describe the issue:

I have a Modal with various click-targets inside it. With keyboard navigation I can tab between the different click/tab-targets. In the modal I also have an iframe, but this will not be included in the tab-order by default. If I set tabindex=”0” on the iframe, the iframe will be included in the tab-order. BUT this will break the FocusTrap on the Modal to also include tab targets in the browsers command bar. So, I can tab into the iframe and reach the tab targets there, but when tabbing out of the iframe the first tab-stop will be in the browser command-bar (“Tabs you’ve set aside” for Edge). This only happens if the iframe is the last tab-target in the Modal. If there are tab-targets after the iframe, the tabbing works fine and wraps around inside the modal.

#### Actual behavior:

Tabbing inside a Modal with an iframe as the last element will also include tab-targets of the browser command bar. 

#### Expected behavior:

Tabbing in a Modal should only cycle between tab-targets inside the Modal (even with an iframe at the end)

**Comment by KevinTCoughlin** [comment]
The tab experience on that page isn't clear to me, but have you tried setting the iframe's tabindex to `-1` if you want to avoid it tabbing? Maybe I'm not fully understanding the expected behavior here, if so my apologies.

**Comment by Anschur** [comment]
I DO want to have the iframe in the tab-order, so setting tabindex to -1 is not a solution. Normal behavior in a Modal is to have tab only move between the tab-targets that are inside the modal - and that is what I would like. But if the last element in the Modal is an iframe that is a tab-stop, tabbing will take you out of the modal and move on to tab-targets that are on the "command-bar" of the actual browser. So you would have to tab through the URL input++ in order to get back to the modal. As a work around I have now added a button after the iframe. Since this button is a tab-target and is after the iframe, tabbing will then stay put inside the modal, and not move on to the browser bar.

**Comment by michaelangotti** [comment]
@dzearing Can any of your (new) team look at this?

**Comment by kenotron** [comment]
Is this still an issue, @anschur? I saw that you have a "Close" button on the bottom. Is this a button you're trying to get rid of (since this would make the iframe the last component in the modal)?

**Comment by JasonGore** [comment]
@Anschur Which version of Fabric have you seen ChoiceGroup breaking out? ChoiceGroup breaking out of Panel should have been resolved with #5842. If you can repro in a CodePen we should probably break that out as a separate issue. Thanks!

**Comment by Vitalius1** [comment]
The issue still exists. @JasonGore as you already fixed a similar issue could you take a look?

**Comment by mikewheaton** [comment]
Here is a [repro of the issue](https://6wwq866n9r.codesandbox.io/) (edit it [here](https://codesandbox.io/s/6wwq866n9r)).

I can confirm that in Chrome and Edge, when tabbing inside the Modal the focus enters the iframe, goes over every element in the iframe, and then comes back out to the browser itself. The expected behavior is that the FocusTrapZone keeps focus inside the Modal.

**Comment by micahgodbolt** [comment]
@davidGuerreroDelRio Is this something you could help with or give some insight?
