### ISSUE TITLE
ChoiceGroup: focus is wrong when using ChoiceGroup inside of Panel

### ISSUE THREAD

**Issue by SumiranAgg** [OfficeDev/office-ui-fabric-react#5160]
### Bug Report

OS: Windows 10 RS3
OS version: build 16299.371
Browser: Microsoft edge browser
Edge version: Microsoft Edge 41.16299.371.0
Firefox version: 59.0.2 (32-bit)
Version:20180413T115929

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No)
No

Requested priority: (Blocking, High, Normal, Low) 
Normal

Products/sites affected: (if applicable)
VSTS

Describe the issue:
Panel focus order is improper when choice group is rendered within the Panel.

Actual behavior:
Suppose you have choice group with options "a" and "b" in the panel.

The focus first goes to cross button of the panel, then the choice group option "a", then tabbing will make you focus the page title/window etc.

If you select option "b" my moving key down, then the focus will remain inside the Panel which is the expected behavior. But by default, as "a" is selected, the focus goes out of the Panel

Expected behavior:
Focus order should remain inside the panel only

**Comment by SumiranAgg** [comment]
Aware that this is duplicate for https://github.com/OfficeDev/office-ui-fabric-react/issues/4191.
Was closed without resolution hence re-opening.
PLEASE DO NOT CLOSE AS DUP.

**Comment by JasonGore** [comment]
#4938 possible related. I will take a look at soon.

**Comment by aditima** [comment]
@JasonGore - this PR by @bworline fixed something very similar: https://github.com/OfficeDev/office-ui-fabric-react/pull/4898 . Could you please check if this is already fixed?

**Comment by JasonGore** [comment]
This still appears to be an issue. Here is a [CodePen](https://codepen.io/jasongore/pen/rrqWGZ) with repro.

**Comment by JasonGore** [comment]
This is only occurs when ChoiceGroup is the last element within Panel. If there are any other elements after ChoiceGroup, tabbing out of ChoiceGroup selects the the next element.

Further analysis shows that FocusTrapZone is not detecting ChoiceGroup as a whole as the last tabbable child, only the last ChoiceGroupOption. As a result, FocusTrapZone does not trap tabs from any other ChoiceGroupOption, which ends up highlighting the next element outside of FocusTrapZone.

**Comment by JasonGore** [comment]
This issue will again occur with the merge of #8053. This issue will remain closed but is covered by #8055.
