### ISSUE TITLE
Dropdowns do not open list of items

### ISSUE THREAD

**Issue by twaddell** [OfficeDev/office-ui-fabric-react#611]
- Firefox 50.0 Windows 10
- Chrome 54.0.2840.99 Windows 10

When clicking on a Dropdown component the list of items does not display.
Keyboard up/down still functions correctly and allows scrolling through items.

This is also occurring on the [Dropdown example page](http://dev.office.com/fabric#/components/dropdown)

**Comment by biogenez** [comment]
same problem in IE & Edge

**Comment by dzearing** [comment]
This has been fixed in the latest build. The issue wasn't related to dropdown, but manifested from LayerHost not being positioned correctly at 0, 0 fixed, which was causing layered content to scroll the page up, which would in turn cause onDismiss to fire.

It's pretty simple to work around; you can either update to the latest build, or just add the style on your page:

```css
.ms-LayerHost-overlay {
  position: fixed;
  z-index: 1000000; /* layered content should overlay other content. */
}
```

The site will be patched next week.

**Comment by twaddell** [comment]
Still occurs on 0.77.1

I use the following code snippets on my page:
`import { Dropdown } from "office-ui-fabric-react/lib/Dropdown"`

`<Dropdown
label='Basic example:'
options={
  [
    { key: 'A', text: 'Option a' },
    { key: 'B', text: 'Option b' },
    { key: 'C', text: 'Option c' },
    { key: 'D', text: 'Option d' },
    { key: 'E', text: 'Option e' },
    { key: 'F', text: 'Option f' },
    { key: 'G', text: 'Option g' },
    { key: 'H', text: 'Option h', isSelected: true },
    { key: 'I', text: 'Option i' },
    { key: 'J', text: 'Option j' },
    ]
    }
/>`

When clicking on the dropdown `<span class="ms-Layer"></span>` is created but contains no items.
This results in a small box appearing as in the screenshot below:

<img width="350" alt="dropdown" src="https://cloud.githubusercontent.com/assets/18006230/20664972/8c94d41c-b555-11e6-8b57-1202c2f2d07b.PNG">

**Comment by dzearing** [comment]
It is supposed to render the content at the end of your DOM within the layerhost element. If you inspect BODY's last child, it should be in there. I'm not reproing in any of our environments so an isolated repro would be useful.

**Comment by mibes** [comment]
This pen demonstrates the dropdown issue: http://codepen.io/mibes/pen/PbJQRK
It uses build 0.78.1.

The issue only manifests itself (for me) when the dropdown is near the bottom of the page. The fix that was included in build 0.77 works on both Chrome (v.54.0.2840.98) and Firefox (v.50.0), but the issue remains on Safari (v.10.0.1) -- all on OSX.

**Comment by mibes** [comment]
Not sure if this is useful, but if you disable closing the dropdown in `onDismiss` in the Dropdown.js it shows the different behaviour in Safari:

` Dropdown.prototype._onDismiss = function () { `
`        // this.setState({ isOpen: false }); `
` };`


With this function disabled: in Safari when you click a Dropdown near the bottom of the page, it scrolls to the top of the page and then shows the Dropdown content at the bottom of the window. I suspect it's the scrolling that triggers the onDismiss and hence the Dropdown is closed again.

**Comment by twaddell** [comment]
My appologies, although I had updated fabric-react I was linking to an old version of the fabric css. I have updated the css to 5.0.1 and all is working for me now with build 0.78.1

**Comment by dzearing** [comment]
Awesome, glad to hear.
